version: '3.4'

services:
  benevarts.web:
    image: ${DOCKER_REGISTRY-}benevartsweb
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
      - DOTNET_ROOT=/root/.dotnet
    networks:
      - my_network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: BenevArtsptg
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - c:/temp/pgdata:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network: