version: '3.4'
services:
  benevarts.web:
    image: benevartsimage:1.2
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=BenevArtsptg;Username=postgres;Password=Brutalista1!;
    networks:
      - my_network

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: BenevArtsptg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Brutalista1!
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:
